### ISSUE TITLE
[Question] Have you tried RF communications?

### ISSUE THREAD

**Issue by imduffy15** [ttroy50/pyephember#10]
Hi Thom,

Love your work here. Have you tried using something like a Sonoff RF bridge to build your own WiFi gateway to replace the EPH one in order to get all the data without any requirement for an internet connection?

I'm researching heating systems and am finding it difficult to find a no internet connection based solution. Thought EPH came close but haven't seen anyone do it via RF yet so may have to break new ground. 

Thanks,
Ian.

**Comment by ttroy50** [comment]
I haven't tried to connect directly via RF and for my use cases the cloud API is ok.
