### ISSUE TITLE
Switching boiler on/off

### ISSUE THREAD

**Issue by SquishyMucus** [ttroy50/pyephember#16]
Hi, I'm trying to use the EPH controller with Home Assistant. As there are issues there I'm currently just trying to run the functionality using your library from a simple python script. I have hit a bit of a brick wall in terms of debugging.

**Note:** I've also given up on any advanced functionality and all I'll want to do is to turn the heating on and off from home assistant, the temperature on the boiler I'll preset and the TVRs are all smart already.

My EPH controller currently has only one zone (as it's a single zone device) called 'WholeHouse'

**Code Sample:**
```
zoneName = "WholeHouse"
t = EphEmber('<my@email>', '<my_password>')
print("{} current temperature is {}".format(zoneName, t.get_zone_temperature(zoneName)))
print("{} target temperature is {}".format(zoneName, t.get_zone_target_temperature(zoneName)))
print("{} mode : {}".format(zoneName, t.get_zone_mode(zoneName).name))
t._set_zone_mode(zoneName, 2)
print("{} mode : {}".format(zoneName, t.get_zone_mode(zoneName).name))
```

**Result:**
```
WholeHouse current temperature is 23.9
WholeHouse target temperature is 5.0
WholeHouse mode : OFF
Traceback (most recent call last):
  File "E:\dev\eph\test.py", line 16, in <module>
    t._set_zone_mode(zoneName, 2)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\dev\eph\pyephember\pyephember\pyephember.py", line 585, in _set_zone_mode
    return self.messenger.send_zone_commands(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\dev\eph\pyephember\pyephember\pyephember.py", line 376, in send_zone_commands
    return self._zone_command_b64(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\dev\eph\pyephember\pyephember\pyephember.py", line 286, in _zone_command_b64
    "mac": zone['mac'],
           ~~~~^^^^^^^
TypeError: string indices must be integers, not 'str'
```

The error is in the '_zone_command_b64' function in the library.
```
msg = json.dumps(
            {
                "common": {
                    "serial": 7870,
                    "productId": product_id,
                    "uid": uid,
                    "timestamp": str(int(1000*time.time()))
                },
                "data": {
                    "mac": zone['mac'],
                    "pointData": cmd
                }
            }
```

Problem is that there is no zone entry for 'mac', the if I print out the contents of zone inside the function above:
`print(zone)`

The result returns 'WholeHouse'

I'm therefore trying to figure out what value I should put there. I have tried the following:
```
 "data": {
                    "mac": <MY_TRIAL_VALUES_GO_HERE>,
                    "pointData": cmd
                }
```
- ' ' and '' (mac: '' and mac: ' ')
- 0 (mac: zone[0])
- 'WholeHouse' (mac: 'WholeHouse', mac: zone['WholeHouse'] gives the same error)
- the MAC address off the side of the EPH WiFi controller (mac: 'XXXXXXXXXXXXXX')

In all cases the application runs fine but nothing happens, no error but also no result. 

I would appreciate any suggestions you might have here.

**Comment by rupertleveneucd** [comment]
Could you try with set_zone_mode (no leading underscore) instead of _set_zone_mode ?

**Comment by SquishyMucus** [comment]
That was it, thanks a ton. That will teach me to call 'private' methods.
