### ISSUE TITLE
example code gives AttributeError

### ISSUE THREAD

**Issue by rupertleveneucd** [ttroy50/pyephember#8]
Since the recent update (for which, many thanks), the example code in the phpember.py comment
```
    Example usage: t = EphEmber('me@somewhere.com', 'mypasswd')
                   t.getZoneTemperature('myzone') # Get temperature
```
gives `AttributeError: 'EphEmber' object has no attribute 'getZoneTemperature'`.

**Comment by ttroy50** [comment]
It should be `t.get_zone_temperature('myzone')`. I change dto pascal case a few updates ago. 'll update the comment.

**Comment by eiregrime** [comment]
I appreciate all your job and input into this while I'm just looking from the side. Do you have any idea when that will be included in home-assistant update as yesterday's 101.3 ver didn't have it?

**Comment by ttroy50** [comment]
The fixes have been accepted into the dev branch of home-assistant. I'm not 100% sure on the current release process of home-assistant but it looks like the 102 beta may be due next Wednesday with the full release of 102 on the 20th. I'd hope the changes will be included in that.

If you wanted to use them now you could take the changes I've pushed to home-assistant and create a custom component with a slightly different name.

**Comment by eiregrime** [comment]
Thanks once more time, I'll probably do that this weekend.

**Comment by ttroy50** [comment]
fixed this now.

From checking with the HA devs on discord, my fix should be in the 102 version scheduled for beta next week.
